ect_demo/ect_demo/urls.py
from django.contrib import admin
from django.urls    import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ect_tool.urls')),
]

ect_demo/ect_tool/urls.py
#   App Name:   Endometrial Cancer Tool (Demo)
#   Author:     Xavier Llobet Navàs
#   Content:    ECT (Demo) urls
#
# - This file contains all the paths for Endometrial Cancer Tool (Demo)
#   will use to serve the views:
#
# =====================================================================
# IMPORTS
# =====================================================================

from django.urls                import path, include
from django.conf                import settings
from django.conf.urls.static    import static
from .                          import views

# =====================================================================
# PATHS
# =====================================================================

app_name        = 'ect'
urlpatterns     = [
    
        path("accounts/", include("django.contrib.auth.urls")),
        
        # ex: /ect_tool/
        path(   '',                                    
                views.index,                        
                name='index'),
        path(   'ect_tool/',                             
                views.index,                        
                name='index'),

        # /ect_tool/ect/
        path(   'ect_tool/ect/',                    
                views.ect,                     
                name='ect'),

        # /ect_tool/cite_us/
        path(   'ect_tool/cite_us/',                    
                views.cite_us,                     
                name='cite_us'),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ect_demo/ect_tool/models.py
from django.db import models

# Create your models here.

ect_demo/ect_tool/views.py
#   App Name:   Endometrial Cancer Tool (Demo)
#   Author:     Xavier Llobet Navàs
#   Content:    ECT (Demo) views
#
# - This file contains all the Django framework views for the 
#   Endometrial Cancer Tool (Demo).
#
# - The views are divided in different fields/sections:
#
#   - Home
#   - EC Tool
#   - Cite Us
#
# - Home site for a summary of the ECT purpose and the data used.
#
# - EC Tool (Demo), can plot with no need of statistical knowledge, Progression-Free
#   and Overall survival for some clinical categories.
#
# =====================================================================
# IMPORTS
# =====================================================================

from            django.shortcuts            import  render
import          pandas                          as  pd
from .  import  ut_constants                    as  cns
from .  import  ut_survival                     as  surv


# =====================================================================
# HOME FIELD VIEW
# =====================================================================

# Home view:
# ---------------------------------------------------------------------
def index(request):
    '''
    This function return the home view were to see a brief
    description of the Endometrial Cancer Tool (Demo) purpose.
    '''

    if request.method == 'GET':
        
        # Template context date
        context:    dict    = { 'title':    'Endometrial Cancer Tool (Demo)',
                                'field':    'home'}

        return render(request, 'ect_tool/base_home.html', context)
    
    if request.method == 'POST':

        # Template context date
        context:    dict    = { 'title':    'Endometrial Cancer Tool (Demo)',
                                'field':    'home'}

        return render(request, 'ect_tool/base_home.html', context)
    
# ---------------------------------------------------------------------
def ect(request):
    '''
    View to generate plots about Endometrial Cancer with TCGA data.
    '''

    if request.method == 'GET':

        # Template context date
        context:    dict    = { 'title':    'Endometrial Cancer Tool (Demo)',
                                'field':    'ect'}

        return render(request, 'ect_tool/base_ect.html', context)

    # New
    if request.method == 'POST':

        # Get input values
        mode:           str             = request.POST['survival_type']
        clinical_cat:   str             = request.POST['clinical_category']

        # Sorting the survival dataframe by the PFS
        df:             pd.DataFrame    = cns.SURVIVAL
        sorted_df:      pd.DataFrame    = df.sort_values(by=f'{mode}_months', ascending=True)

        # Entire category name:
        main_category:  str             = cns.CATEGORIES_DICT[clinical_cat]
                    
        # Molecular subtype categories:
        subtype_catgs:  list[str]       = cns.SURVIVAL_GROUPS[clinical_cat]
        
        # Template context data
        context:        dict            = surv.km_category_survival_helper( sorted_df, 
                                                                            mode,
                                                                            clinical_cat,
                                                                            main_category,
                                                                            subtype_catgs)
        
        context['title']                = 'Endometrial Cancer Tool (Demo)'
        context['field']                = 'ect'

        return render(request, 'ect_tool/base_ect.html', context)
    
# ---------------------------------------------------------------------
def cite_us(request):
    '''
    View that shows how to cite this web application.
    '''

    if request.method == 'GET':
        # Template context date
        context:    dict    = { 'title':    'Endometrial Cancer Tool (Demo)',
                                'field':    'cite_us'}

        return render(request, 'ect_tool/base_cite_us.html', context)

    if request.method == 'POST':
        # Template context date
        context:    dict    = { 'title':    'Endometrial Cancer Tool (Demo)',
                                'field':    'cite_us'}

        return render(request, 'ect_tool/base_cite_us.html', context)

ect_demo/ect_tool/templates/ect_tool/base.html
<!DOCTYPE html>
<html lang="en">

    <!-- HEAD -->
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>  
        
        <!-------------------------- 
            JAVASCRIPT AND JQUERY 
        --------------------------->
        {% load static %}
        <script src="{% static 'ect_tool/vendor/jquery/jquery-3.6.1.min.js' %}"></script>
        {% load static %}
        <link rel="stylesheet" href="{% static 'ect_tool/vendor/jquery-ui-1.13.2/jquery-ui.min.css' %}">
        {% load static %}
        <script src="{% static 'ect_tool/vendor/jquery-ui-1.13.2/jquery-ui.min.js' %}"></script>        
        {% load static %}
        <link rel="stylesheet" href="{% static 'ect_tool/css/index.css' %}">

        <title>{{title}}</title>

    </head>

    <!-- BODY -->
    <body>
        <div class="row m-0 p-0">
            <!-- HEADER -->
            <header class="row p-0 m-0">
                <div class="row h-100 m-0 p-4 pt-2">
                    <div class="col-1 m-0 p-0 pt-2">
                    </div>
                    <div class="col-10 m-0 p-4 pt-0 ps-0">
                        <h1 class="m-0 ms-2 mt-4 p-0 pt-1 display-4 text-center title">{{title}}</h1>
                    </div>
                    <div class="col-1 m-0 p-0 pt-3 pe-1 logo_column">                        
                        {% load static %}
                        <img src="{% static 'ect_tool/img/xavi_3.drawio.svg' %}" class="img-fluid float-end third_img" alt="Xavier Llobet">
                        {% load static %}
                        <img src="{% static 'ect_tool/img/xavi_2.drawio.svg' %}" class="img-fluid float-end second_img" alt="Xavier Llobet">
                    </div>
                </div>            
            </header>

            <div class="row p-0 m-0 text-center border-bottom topmenu_bg">
                <small><p class="m-0 p-2 apps">
                    <a class="m-0 p-0" href="{% url 'ect:index' %}">Home</a>
                    <a class="m-0 p-0 ps-4" href="{% url 'ect:ect' %}">EC Tool</a>
                    <a class="m-0 p-0 ps-4" href="{% url 'ect:cite_us' %}">Cite Us</a>
                </p></small>
            </div>

            <!-- FIRST ROW: TOOLS MENU AND MAIN FORMS -->
            <div class="row m-0 p-0 pb-4 mb-4">

                <!-- CENTRAL MAIN FORM OPTIONS -->
                
                {% if field == 'home' %}
                    <div class="col-12 m-0 p-0">
                        <div class="row m-0 p-0" id="home">
                            {% block home %}
                            {% endblock home %} 
                        </div>
                    </div>
                {% endif %}

                {% if field == 'ect' %}
                    <div class="col-12 m-0 p-0">
                        <div class="row m-0 p-0 ps-1 pe-1" id="ect">
                            {% block ect %}
                            {% endblock ect %} 
                        </div>
                    </div>
                {% endif %}

                {% if field == 'cite_us' %}
                    <div class="col-1 m-0 p-0">
                    </div>
                    <div class="col-9 m-0 mb-4 p-0 pt-2 pb-4">
                        <div class="row m-0 p-0 pe-2" id="cite_us">
                            {% block cite_us %}
                            {% endblock cite_us %} 
                        </div>
                    </div>
                {% endif %}

            </div>  

            <div class="row m-0 mt-4 mb-4 p-0 pb-4 mb-4"></div>            

            <!-- FOOTER -->
            <footer class="row m-0 mt-4 p-4 pb-3">
                <div class="row m-0 p-4 w-100 h-100 text-center">
                    <div class="col-4 m-0 p-0 text-start">
                    </div>
                    <div class="col-4 m-0 p-0">
                        <p class="fs-6 p-4 text-white"><small>Copyright &copy 2025 Xavier Llobet</small></p>
                    </div>
                    <div class="col-4 m-0 p-0 text-end">
                        <p class="fs-6 p-4 text-white"><small>Developed by <a class="link-info" href="https://www.linkedin.com/in/xavier-l-455975223/">Xavier Llobet</a></small></p>
                    </div>                
                </div>
            </footer>
        </div>
    </body>
</html>

ect_demo/ect_tool/templates/ect_tool/base_cite_us.html
{% extends "./base.html" %}
{% block cite_us %}

<p class="m-0 p-0 pt-2 pb-2 fs-4 text-dark border-bottom">How to cite this site</p>
<p class="mt-2 fs-6 text-dark"><small>Francisco J Llobet, 2025, <i>{{title}}</i>, 'https://github.com/P4kD3v/ect_demo'.</small></p>

{% endblock cite_us %}

ect_demo/ect_tool/templates/ect_tool/base_ect.html
{% extends "./base.html" %}
{% block ect %}

<div class="row m-0 p-0">
    <h2 class="w-100 m-0 p-3 pb-2 ps-4 pe-4 fs-3 text-center rounded-top text-white topmenu">EC Tool<br><p class="mt-2 ms-4 me-4 ps-4 pe-4 fs-6"><small>Do a survival analysis of the Endometrial Cancer disease by different clinical patient data as grade, stage, hitologic type, molecular subtype and age.</small></p></h2>
    <div class="col-2 m-0 p-0 rounded border-top">
        <p class="w-100 m-0 p-2 fs-6 text-center rounded-top result_headers text-white border-bottom" for="analysis_type">
            <small>Fields</small>
        </p>
        <form id="overview_form" class="m-0 p-0 w-100 text-center" action="{% url 'ect:ect' %}" method="post"> 
            {% csrf_token %}
            <p class="m-0 p-0 p-2 text-center fs-4 rounded-top topmenu text-white border-bottom"><small>Overview</small></p>
            <div class="w-100 m-0 p-0">
                <label class="w-100 p-2 fs-6 text-center select_labels text-white rounded-top" for="analysis_type">
                    <small>Select analysis</small>
                </label>
                <select class="w-100 form-select form-select-sm text-center rounded-0 rounded-bottom" name="survival_type" id="analysis_type">
                    <option value="os" selected><small>Overall Survival</small></option>
                    <option value="pfs"><small>Progresion-Free Survival</small></option>
                </select>
                            
            </div>
            <div class="w-100 m-0 p-0 pt-1">
                <label class="w-100 p-2 fs-6 text-center select_labels text-white rounded-top" for="analysis_type">
                    <small>Select category</small>
                </label>
                <select class="w-100 form-select form-select-sm text-center rounded-0 rounded-bottom" name="clinical_category">
                    <option value="grade" selected><small>By Grade</small></option>
                    <option value="tumor_type"><small>By Histological Type</small></option>
                    <option value="mol_subtype"><small>By Molecular Subtype</small></option>
                    <option value="stage"><small>By Stage</small></option>
                    <option value="radiotherapy"><small>By Radiation Therapy</small></option>
                    <option value="age_group"><small>By Age</small></option>
                    <option value="bmi_status"><small>By BMI</small></option>
                </select>
            </div>
            <button class="btn btn-success w-100 btn-sm mt-1 mb-0 p-1 fs-6" id="scroll_overview" name="show" type="submit"><small>Plot</small></button>
        </form>

    </div>
    <div class="col-10 m-0 p-0 border-start">
        <p class="w-100 m-0 p-2 fs-6 text-center border-top rounded-top result_headers text-white" for="analysis_type">
            <small>Result</small>
        </p>
        <div class="row m-0 p-0">
            <div class="col-7">
                {{survival_plot|safe}}
                {% if table_plot %}
                    <div class="row m-0 p-0 ps-2 pb-4 pe-0 me-0 border-bottom"> 
                            <p class="ms-3 mb-0 pb-0 fs-5 fw-bold text-dark text-opacity-75"><small>Population at risk by time</small></p>
                            <table style="width: 85%;" class="table table-light pe-0 ms-4 me-0">
                                {% for row in table_plot %}
                                    {% if row.0 == 'Months' %}
                                        <tr style="color: cadetblue;">
                                            {% for item_data in row %}
                                                {% if item_data == 'Months' %}
                                                    <th class="text-start align-middle" style="width: 16%;"><small>{{item_data}}</small></th>
                                                {% else %}
                                                    <th class="text-center align-middle"><small>{{item_data}}</small></th>
                                                {% endif %}
                                            {% endfor %}
                                        </tr>
                                    {% else %}
                                        <tr>
                                            {% for item_data in row %}
                                                {% if item_data.0 %}
                                                    <td class="text-start fw-bold align-middle" style="font-size: 0.9em;"><small>{{item_data}}</small></td>
                                                {% else %}
                                                    <td class="text-center align-middle" style="font-size: 0.9em;"><small>{{item_data}}</small></td>
                                                {% endif %}
                                            {% endfor %}
                                        </tr>
                                    {% endif %}
                                {% endfor %}
                            </table>                        
                    </div>
                {% endif %}
            </div>
            <div class="col-5">
                {{bar_plot|safe}}
            </div>
        </div>
   
    </div>
</div>
{% endblock ect %}

ect_demo/ect_tool/templates/ect_tool/base_home.html
{% extends "./base.html" %}
{% block home %}

<div class="row m-0 p-0">
    <div class="col-2 m-0 p-0">
    </div> 
    <div class="col-8 m-0 p-0">
        <small>
            <p class="w-100 m-0 mt-4 p-4 pt-3 pb-3 fs-4 text-center rounded-top border-bottom border-secondary fw-bold">
                Endometrial Cancer Tool (Demo) description
            </p>
            <p class="w-100 m-0 p-0 pt-3 fs-6 text-dark" style="text-align: justify;">
            <small>The Endometrial Cancer Tool (Demo) is a cutting-edge web application designed for 
                researchers, clinicians, and epidemiologists to statistically analyze this disease 
                survival data and generate comprehensive survival plots.</small>
            </p>

            <p class="w-100 m-0 p-0 pt-3 fs-6 text-dark" style="text-align: justify;">
                <small>This intuitive platform simplifies the complex process of survival analysis, 
                    making it accessible to users with varying levels of statistical expertise.
                    Users can easily create plots with no need of previous bioinformatic or statistics
                    knowledge.</small>
            </p>

            <p class="w-100 m-0 p-0 pt-3 fs-6 text-dark" style="text-align: justify;">
                <small>The core feature of ECT (Demo) is its powerful Kaplan-Meier estimator, 
                    which allows users to visualize survival functions over time.
                    Through an easy-to-use interface, users can customize survival plots by 
                    selecting variables such as grade, hystologic type, molecular subtype and stage.</small>
            </p>

            <p class="w-100 m-0 p-0 pt-3 fs-6 text-dark" style="text-align: justify;">
                <small>The application also supports advanced statistical methods, including 
                    Mann-Witney U, Hazard Ratio and log-rank p-value tests, to compare survival curves 
                    and assess the impact of covariates on survival outcomes.
                    Also it offers dynamic and interactive visualizations, where users can adjust 
                    time scales, zoom in, zoom out or select an area to study, enabling users to 
                    explore data effectively.</small>
            </p>

            <p class="w-100 m-0 p-0 pt-3 fs-6 text-dark" style="text-align: justify;">
                <small></small>
            </p>

            <p class="w-100 m-0 p-0 pt-3 pb-4 fs-6 text-dark" style="text-align: justify;">
                <small>Additionally, the platform supports the export of high-resolution plots, made with Dash/Plotly, 
                    suitable for publications or presentations.</small>
            </p>
            
        </small>      
    </div>
    <div class="col-2 m-0 p-0">
    </div> 
</div>

{% endblock home %}